POST http://localhost:8001/api/auth/register/
Content-Type: application/json

{
    "email": "ezemehenry20@gmail.com",
    "password": "hello123"
}
###
POST http://localhost:8001/api/auth/register/
Content-Type: application/json

{
    "email": "ezeme20@gmail.com",
    "password": "hello123"
}
###
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "email": "ezemehenry20@gmail.com",
    "password": "hello123"
}

###
POST http://localhost:8001/api/auth/login/
Content-Type: application/json

{
    "email": "ezemechidubem@gmail.com",
    "password": "Ozomo999"
}

###
POST http://localhost:8001/api/auth/login/

Content-Type: application/json

{
    "email": "ezeme20@gmail.com",
    "password": "hello123"
}
###

POST http://localhost:8001/api/notes/categories/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODk4NjUzLCJpYXQiOjE3ODA4OTc3NTMsImp0aSI6ImEyZjFmNjMxODg2ZjRjMmJhMTIxMzQyODcyN2QzYWZlIiwidXNlcl9pZCI6IjUifQ.3lcYTpJ6RhbEe_jejpKyZaQJJdIpOKMul0MyyqSzzws

{
    "name": "Work",
    "description": "Notes related to work"
}
###

GET http://localhost:8001/api/notes/categories/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODk4NjUzLCJpYXQiOjE3ODA4OTc3NTMsImp0aSI6ImEyZjFmNjMxODg2ZjRjMmJhMTIxMzQyODcyN2QzYWZlIiwidXNlcl9pZCI6IjUifQ.3lcYTpJ6RhbEe_jejpKyZaQJJdIpOKMul0MyyqSzzws

###
POST http://localhost:8001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODU4ODA1LCJpYXQiOjE3ODA4NTc5MDUsImp0aSI6IjJhNTBkNDQwNzg3OTRmZTlhMDI0NDc1YWZlNzJiNzQxIiwidXNlcl9pZCI6IjUifQ.YDbKMbKJfCe4ZOqyScHUs4TlPQ3XHaeHRzC5jzPBsl8

{
    "title": "First Note",
    "content": "This is the content of the first note.",
    "category": 
}
###
POST http://localhost:8001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODU4ODA1LCJpYXQiOjE3ODA4NTc5MDUsImp0aSI6IjJhNTBkNDQwNzg3OTRmZTlhMDI0NDc1YWZlNzJiNzQxIiwidXNlcl9pZCI6IjUifQ.YDbKMbKJfCe4ZOqyScHUs4TlPQ3XHaeHRzC5jzPBsl8

{
    "title": "First Note",
    "content": "This is the content of the first note.",
    "category": 1
}
###
POST http://localhost:8001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODU4ODA1LCJpYXQiOjE3ODA4NTc5MDUsImp0aSI6IjJhNTBkNDQwNzg3OTRmZTlhMDI0NDc1YWZlNzJiNzQxIiwidXNlcl9pZCI6IjUifQ.YDbKMbKJfCe4ZOqyScHUs4TlPQ3XHaeHRzC5jzPBsl8

{
    "title": "Second Note",
    "content": "This is the content of the second note.",
    "category": 1
}

###
GET http://localhost:8001/api/notes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODk4MDU5LCJpYXQiOjE3ODA4OTcxNTksImp0aSI6Ijc2OTlmYTBjZmM0YzQ2ZWViNzlmNzFiYjdiZmY2OWNkIiwidXNlcl9pZCI6IjUifQ.FPNIKf2XgS4SJJGz9gU57Ry-kvGjppL4o0jmfMMyjOQ       

###
GET http://localhost:8001/api/notes/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODU4ODA1LCJpYXQiOjE3ODA4NTc5MDUsImp0aSI6IjJhNTBkNDQwNzg3OTRmZTlhMDI0NDc1YWZlNzJiNzQxIiwidXNlcl9pZCI6IjUifQ.YDbKMbKJfCe4ZOqyScHUs4TlPQ3XHaeHRzC5jzPBsl8

###
POST http://localhost:8001/api/notes/1/share/
Content-Type: application/json
Authorization: Bearer <token>

{
    "target_user_id": 2
}
###
GET http://localhost:8001/api/notes/shared/
Authorization: Bearer <token>
###
GET http://localhost:8001/api/notes/myshared/
Authorization: Bearer <token>
###

POST http://localhost:8001/api/notes/2/send-email/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgwODk4MDU5LCJpYXQiOjE3ODA4OTcxNTksImp0aSI6Ijc2OTlmYTBjZmM0YzQ2ZWViNzlmNzFiYjdiZmY2OWNkIiwidXNlcl9pZCI6IjUifQ.FPNIKf2XgS4SJJGz9gU57Ry-kvGjppL4o0jmfMMyjOQ

{
    "recipient_email": "cezeme.2200675@stu.cu.edu.ng"
}