# Generated by Django 6.0.5 on 2026-05-31 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0002_notesharing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NoteSharing",
            new_name="NoteShare",
        ),
        migrations.RenameField(
            model_name="noteshare",
            old_name="shared_with",
            new_name="target",
        ),
    ]
