# Generated by Django 6.0.6 on 2026-06-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_noteshare_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteupload',
            name='file_type',
            field=models.CharField(choices=[('image/png', 'PNG'), ('image/jpeg', 'JPEG'), ('image/jpg', 'JPG'), ('application/pdf', 'PDF'), ('text/plain', 'TXT')], max_length=50),
        ),
    ]
