# Generated by Django 5.2.1 on 2026-06-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0003_alter_noteupload_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noteupload",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("image/png", "PNG"),
                    ("image/jpeg", "JPEG"),
                    ("image/jpg", "JPG"),
                    ("text/plain", "TXT"),
                    ("application/pdf", "PDF"),
                ],
                max_length=50,
            ),
        ),
    ]
