# Generated by Django 5.2.1 on 2026-07-05 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0005_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating",
            old_name="ratings",
            new_name="rating",
        ),
        migrations.AddConstraint(
            model_name="rating",
            constraint=models.UniqueConstraint(
                fields=("note", "user"), name="unique_note_user_rating"
            ),
        ),
    ]
