# Generated by Django 5.2.1 on 2026-07-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("note", "0006_rename_ratings_rating_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteSharedHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("google_drive", "Google Drive"),
                            ("onedrive", "OneDrive"),
                        ],
                        max_length=50,
                    ),
                ),
                ("destination", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_history",
                        to="note.note",
                    ),
                ),
            ],
        ),
    ]
