# Generated by Django 5.2.1 on 2026-06-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermodel",
            name="first_name",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="customermodel",
            name="last_name",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
