# Generated by Django 5.2.1 on 2026-07-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0002_customermodel_first_name_customermodel_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermodel",
            name="google_credentials",
            field=models.TextField(blank=True, null=True),
        ),
    ]
