# Generated by Django 5.2.1 on 2026-07-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0003_customermodel_google_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermodel",
            name="onedrive_credentials",
            field=models.TextField(blank=True, null=True),
        ),
    ]
